AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles and details
Parameters:
  InfraStackName:
    Description: Name of an active CloudFormation infra stack that has the kms key
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
  DbStackName:
    Description: Name of an CloudFormation db stack that has the db secret arn
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
Resources:
  WebServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Description: Instance profile used by the web servers
    Properties:
      Path: /
      Roles:
        - !Ref WebServerRole
  WebServerRole:
    Type: AWS::IAM::Role
    Description: The role web server will assume as a part of instance profile
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref SNSPolicy
        - !Ref DBSecretPolicy
        - !Ref CloudWatchLogPolicy
        - !Ref S3Policy
  S3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join [ '-', [ !Ref 'AWS::StackName', 's3-policy' ] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowS3'
            Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:PutObjectAcl"
              - "s3:GetObject"
              - "s3:DeleteObject"
            Resource:
              - Fn::Join:
                  - ''
                  - - Fn::ImportValue: !Sub '${InfraStackName}:ImageBucketArn'
                    - '/*'
  CloudWatchLogPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join [ '-', [ !Ref 'AWS::StackName', 'cw-log-policy' ] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowCW'
            Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:GetLogEvents'
              - 'logs:PutLogEvents'
              - 'logs:DescribeLogGroups'
              - 'logs:DescribeLogStreams'
              - 'logs:PutRetentionPolicy'
            Resource:
              - '*'
  SNSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join [ '-', [ !Ref 'AWS::StackName', '-ws-sns-policy' ] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowSNS'
            Effect: Allow
            Action:
              - 'sns:Publish'
              - 'sns:CreateTopic'
              - 'sns:Unsubscribe'
              - 'sns:Subscribe'
              - 'sns:ConfirmSubscription'
            Resource:
              - '*'
  DBSecretPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join [ '-', [ !Ref 'AWS::StackName', '-ws-db-secret-policy' ] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowSNS'
            Effect: Allow
            Action:
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
            Resource:
              - Fn::ImportValue: !Sub '${DbStackName}:DatabaseSecret'

Outputs:
  WebServerInstanceProfile:
    Description: Instnace profile used by the web server
    Value: !Ref 'WebServerInstanceProfile'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'WebServerInstanceProfile' ] ]

  WebServerRoleArn:
    Description: Instnace profile role used by the web server
    Value: {"Fn::GetAtt": ["WebServerRole", "Arn"] }
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'WebServerRoleArn' ] ]
